### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8088

### ISSUE THREAD

**Issue by nmtuan200793** [splunk/splunk-javascript-logging#11]
// Change to require("splunk-logging").Logger;
var SplunkLogger = require("splunk-logging").Logger;

/**
- Only the token property is required.
  */
  var config = {
  token: "EB96B256-153A-4492-BAEE-765DECC8320B",
  url: "https://localhost:8088"
  };

// Create a new logger
var Logger = new SplunkLogger(config);

Logger.error = function(err, context) {
    // Handle errors here
    console.log("error", err, "context", context);
};

Error: connect ECONNREFUSED 127.0.0.1:8088 when I send a payload.
Could you please help me.

**Comment by shakeelmohamed** [comment]
@nmtuan200793 are you able to send events over curl? ie:

```shell
 curl -v -k https://localhost:8088/services/collector -H "Authorization: Splunk EB96B256-153A-4492-BAEE-765DECC8320B"  -d '{"event": "test event"}'
```

**Comment by bloodymind** [comment]
I have the same issue, i tried to curl and got this:

$ curl -v -k http://192.168.59.103:8088/services/collector -H "Authorization: Splunk A671A4EF-
DB3A-49AA-8AB0-E8E0487FED31"  -d '{"event": "test event"}'
```
*   Trying 192.168.59.103...
* TCP_NODELAY set
* Connected to 192.168.59.103 (192.168.59.103) port 8088 (#0)
> POST /services/collector HTTP/1.1
> Host: 192.168.59.103:8088
> User-Agent: curl/7.51.0
> Accept: */*
> Authorization: Splunk A671A4EF-DB3A-49AA-8AB0-E8E0487FED31
> Content-Length: 23
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 23 out of 23 bytes
* Recv failure: Connection reset by peer
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by bloodymind** [comment]
@shakeelmohamed any idea about that ?

**Comment by shakeelmohamed** [comment]
@bloodymind have you tried `https`?

**Comment by adrian-gallardo-wizeline** [comment]
@shakeelmohamed, what is it supposed to be the value for `url`?? I was trying with the URL for our splunkcloud account, but I'm receiving `Error: connect ETIMEDOUT`.
The url has the following format: `https://my-account-subdomain.splunkcloud.com`. I also tried adding port `8088` with no success

**Comment by shakeelmohamed** [comment]
@adrian-gallardo-wizeline please contact Cloud support, there is likely a different subdomain for you to use

**Comment by 17puja** [comment]
Error: connect ECONNREFUSED 127.0.0.1:8088 getting error in my postman
