### ISSUE TITLE
strictSSL disabled by default

### ISSUE THREAD

**Issue by magnusjt** [splunk/splunk-javascript-logging#12]
I know the splunk cloud trial doesn't have proper ssl certificates, so it makes some sense to not require it by default. However, i would much rather prefer to have strict security enabled by default, and actively disable it if I want. Or at least mention in the documentation that the default options in this package are not secure.

**Comment by shakeelmohamed** [comment]
Hi @magnusjt,

Thanks for the suggestion.
We've updated the `README.md` and are working on updating the docs on dev.splunk.com to reflect that SSL cert validation is disabled by default.

**Comment by magnusjt** [comment]
Great! Thanks.
