### ISSUE TITLE
NPM request module vulnerability

### ISSUE THREAD

**Issue by subesokun** [splunk/splunk-javascript-logging#15]
Using: `splunk-logging@0.9.2`

splunk-logging is depending on the fixed version `2.61.0` of the request module which has a vulnerability, see the following advisory of NSP https://nodesecurity.io/advisories/309

Is there a special reason why you've version-locked the request module? If not please update as soon as possible.

Thanks a lot!

**Comment by anoff** [comment]
Came across the same issue today in our pipeline. Any chance you guys will fix this?

**Comment by shakeelmohamed** [comment]
We just released v0.9.3 which addresses this, we allow you to use any `2.x.x` version of request now.
