### ISSUE TITLE
Severity being appended to events when not set.

### ISSUE THREAD

**Issue by tbenade** [splunk/splunk-javascript-logging#19]
Hi,

Would like to question the rationale of appending severity to events when severity is not set. Given licensing is per byte of ingestion appending this data to billions of events when not wanted is costing $$. 

Other than a custom formatter is there another way to disable this behaviour?

https://github.com/splunk/splunk-javascript-logging/blob/master/splunklogger.js#L47

Thanks

**Comment by shakeelmohamed** [comment]
@tbenade at this time, the only way of hiding the severity is to use a custom formatter. We believe this is a reasonable workaround.
