### ISSUE TITLE
MemoryLeak HTTPParser

### ISSUE THREAD

**Issue by joaomachado** [splunk/splunk-javascript-logging#20]
Using this configs:
`    maxRetries: 0,
    batchInterval: 5000,
    maxBatchSize: 1024, // kb
    maxBatchCount: 10`
This lib is causing a huge memory leak, Node HTTPParser objects are kept for each HTTP request sent to splunk

**Comment by shakeelmohamed** [comment]
Thanks for the issue @joaomachado, do you have a recommended fix? If so, please send us a PR!

**Comment by joaomachado** [comment]
Not sure what is causing this issue, but a first step should be a complete update of dependencies (mainly request)... There are some security updates too.

**Comment by shakeelmohamed** [comment]
@joaomachado our only dependency is request, and we accept any version that matches `2.x.x` which includes the latest `2.19.1`. You can try running `npm update request` locally and see if that helps. If so, we can add a stricter version check to our `package.json` and issue a patch release.

**Comment by joaomachado** [comment]
Sorry all this noise, this was caused by another lib https://github.com/JarvusInnovations/node-request-to-curl/issues/1

This lib sends a huge number of http requests and was more affected... they wrap http lib :(
