### ISSUE TITLE
no way to set data channel

### ISSUE THREAD

**Issue by samuelt1** [splunk/splunk-javascript-logging#26]
Version of this project you're using: 0.10.1
Platform version Mac OSX 10.14 (18A391)
Framework version: v10.12.0
Splunk version: not sure, but it should be the newest because it was just installed

When I copied and pasted in the tutorial in the readme I got back `Data channel is missing`. According to this help document: https://answers.splunk.com/answers/389554/why-am-i-getting-error-data-channel-is-missing-usi.html. I need to add a channel. There is no built-in way of doing this. maybe I just need to use the whole URL with the channel included?

**Comment by shakeelmohamed** [comment]
Hi @samuelt1, your token is probably configured for indexer acknowledgement. We don't support those kinds of tokens with this library. Please try creating a new HEC token, or disabling indexer ack on the token you're using.

**Comment by samuelt1** [comment]
ok thanks, but just for other people it does work to just add it to the URL like so:
https://<yourSplunkURL>:<yourSplunkPort>/services/collector?channel=<ANY random GUID>
