### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by twonder** [splunk/splunk-javascript-logging#28]
I'm running the basic example with our the token and url values running, and I'm getting a timeout.   This has happened both running locally, as well as running in an AWS Lambda.

Version of this project you're using: 0.10.1
Platform version:  macOS 10.13.6 (Lambda Node.js 8.10)
Framework version: Node.js 8.11.2
Splunk version: 7.0.8.5

I'm able to connect successfully using curl, postman, and a node script using the request-promise library.

**Comment by shilpabijam** [comment]
Thanks, @twonder  for reporting this issue. I am able to successfully run the example locally with Splunk enterprise 7.0.9  and view the logging data in Splunk. To debug this further, could you share your Url details and revisit your HEC setup as specified in http://dev.splunk.com/view/splunk-logging-javascript/SP-CAAAE63.

**Comment by twonder** [comment]
I will touch base with our Splunk administrator to see if I can get some of those details.  I don't want to post our endpoint on github, is there an email I can send it to?

What I find odd is that if the HEC was not set up correctly, why would I be able to successfully call the HEC endpoint (using the same token) using curl, postman and a node script?  We also have other teams in our organization that use the HEC endpoint without error.

**Comment by shakeelmohamed** [comment]
@twonder sure, you can email us at devinfo@splunk.com

**Comment by shilpabijam** [comment]
@twonder, from your script, it seems the url in the config object does not have a port specified, by default the logging library defaults to 8088. Could you specific the port in your url -> for example: http://localhost:8080 and see if this fixes the timeout issue?

**Comment by twonder** [comment]
I tried specifying 8080 and 8088 with no luck.

**Comment by shilpabijam** [comment]
@twonder, could you try 443 instead?

**Comment by twonder** [comment]
That fixed it, thank you.
