### ISSUE TITLE
Metadata Fields Not Supported

### ISSUE THREAD

**Issue by cdowney** [splunk/splunk-javascript-logging#34]
The javascript logger does not support adding "fields" to the metadata as described [here](https://docs.splunk.com/Documentation/SplunkCloud/7.2.7/Data/IFXandHEC)

It looks like it should be as simple as adding a conditional to [here](https://github.com/splunk/splunk-javascript-logging/blob/master/splunklogger.js#L334)

like:
```
if (context.metadata.hasOwnProperty("fields")) {
    metadata.fields = context.metadata.fields;
}
```

Version: 0.10.1
Platform: AWS Lambda
Framework version: Node 10.x
Splunk version: 7.2.6

**Comment by shakeelmohamed** [comment]
Thanks @cdowney, we're open to a PR with some tests if you're interested

**Comment by cdowney** [comment]
Thanks @shakeelmohamed I started working on a branch for a PR, but I'm having issues with the existing integration tests in Travis. They seem to be failing due to a TLS issue.

**Comment by bparmar-splunk** [comment]
Hi All,
Closing this issue because PR #70 supporting this issue has been merged.

Thank you.
