### ISSUE TITLE
Use of API tokens

### ISSUE THREAD

**Issue by khitrenovich** [splunk/splunk-javascript-logging#35]
Looks like this library assumes that the token that was provided is a session token (by sending it along with `Splunk` authentication type). Are there any plans to support API/`Bearer` tokens also?

**Comment by shakeelmohamed** [comment]
Hi @khitrenovich , the HEC endpoint has its own token management isolated from bearer tokens. Feel free to read more: https://dev.splunk.com/enterprise/docs/dataapps/httpeventcollector/
