### ISSUE TITLE
Support for Client-Side Application?

### ISSUE THREAD

**Issue by umcsdon** [splunk/splunk-javascript-logging#4]
Is it possible to use this plugin for Client-Side Javascript Application?

**Comment by bradoyler** [comment]
I suppose you could use browserify to run this module client-side, but don't know if that's supported. Would love to see this as an option for simple logging.
cc: @vashonk

**Comment by bradoyler** [comment]
@umcsdon actually, looks like this: https://github.com/splunk/splunk-sdk-javascript#client-side-code-would be the "supported" option.
But this line: 
```
 var service = new splunkjs.Service({username: "admin", password: "changeme"});
```
has me worried. 
Why would I put a username/password in my client-side app?

**Comment by shakeelmohamed** [comment]
>I suppose you could use browserify to run this module client-side, but don't know if that's supported. Would love to see this as an option for simple logging.

@bradoyler We've manually tested this library with browserify, and it appears to work just fine once you workaround CORS. To workaround CORS on the Splunk end, take a look at this [blog post](http://blogs.splunk.com/2016/05/03/splunk-6-4-using-cors-and-ssl-settings-with-http-event-collector/) by @glennblock.

Once you have browserify installed (`npm install -g browserify`), you can run the following. Then just include `splunk-javascript-logging-client.js` in your web app.

`browserify index.js --standalone SplunkLogger -o splunk-javascript-logging-client.js`

> Why would I put a username/password in my client-side app?

That code example is for a different project, the Splunk SDK for JavaScript, which is not intended to be used in public facing websites.

**Comment by bradoyler** [comment]
@shakeelmohamed Thx. 
I just came across https://github.com/splunk/splunk-bunyan-logger
Would this be a better option?

**Comment by glennblock** [comment]
@bradoyler you'll need to use Browserify to use splunk-bunyan-logger or
splunk-javascript-logging.

As you mentioned, using splunk-sdk-javascript is not ideal as it requires
having valid Splunk login credentials, and having to send them from the
client.

We may add a browser-based logging library in the future. If you'd like to
see that, can you submit an idea at splunkdev.uservoice.com?

Thanks!
Glenn

**Comment by shakeelmohamed** [comment]
@bradoyler Either one will work fine (with browserify). Take a look at the examples in this repo and the bunyan logger repo and see which interface you prefer. Bunyan will automatically give you a bit more metadata as outlined in the examples

**Comment by bradoyler** [comment]
@glennblock @shakeelmohamed Great Thx. I'll try to get CORS enabled and go from there. 🍻

**Comment by bradoyler** [comment]
@umcsdon U can upvote @ https://splunkdev.uservoice.com/forums/235348-dev-platform/suggestions/13751736-event-logging-from-the-browser

**Comment by glennblock** [comment]
Thanks!

**Comment by glennblock** [comment]
I gave you a vote :-)

**Comment by shakeelmohamed** [comment]
@umcsdon @bradoyler you might want to check out this project as it already has browser support https://github.com/vtex/splunkevents-js

**Comment by sylvanaar** [comment]
You can just convert this to a client library by rewriting the post function to just make an AJAX call directly, and merge the source into one file.
