### ISSUE TITLE
requests deprecation

### ISSUE THREAD

**Issue by arcsector** [splunk/splunk-javascript-logging#40]
See [here](https://github.com/request/request/issues/3142) for requests deprecation. Will this be removed as a dependency?

**Comment by shakeelmohamed** [comment]
Hi @arcsector, we've seen that document. The request team has committed to continue making bug fixes, so until there is sufficient need we will not be removing request as a dependency. Our team has been stretched incredibly thin lately and we are our doing our best just to keep up with bugs. That said, I'm going to close the issue as it's not something actionable for us at this time.

Please reach out to us at devinfo@splunk.com if you have any concens.

**Comment by arcsector** [comment]
Got it; thanks guys!
