### ISSUE TITLE
Support for "fields" metadata attribute is missing

### ISSUE THREAD

**Issue by nuttamsingh** [splunk/splunk-javascript-logging#47]
Based on the documentation of the event metadata types in 8.1.1 
https://docs.splunk.com/Documentation/Splunk/8.1.1/Data/FormateventsforHTTPEventCollector

Thanks!

**Comment by Rahmo** [comment]
it doesn't work for me either

**Comment by Rahmo** [comment]
looking at the code I think the problem is in here 
https://github.com/splunk/splunk-javascript-logging/blob/master/splunklogger.js#L353
something about the return I would put it inside the if

**Comment by bparmar-splunk** [comment]
Hi All,
Closing this issue because PR #70 supporting this issue has been merged.

Thank you.
