### ISSUE TITLE
ssh port 443 not allowed

### ISSUE THREAD

**Issue by beaucronin** [splunk/splunk-javascript-logging#5]
We're using this to send events to our Splunk Cloud implementation from AWS Lambda. Our HTTP EC is set up to use port 443, but this port is not allowed by the logger config (which requires port numbers > 1000). I'm working around this by just commenting out this check in our installed copy, but this seems like a bug.

**Comment by shakeelmohamed** [comment]
Hi @beaucronin which version are you using? This should be fixed in v0.9.1

**Comment by beaucronin** [comment]
0.8.0 - I'll upgrade. Thanks!

**Comment by shakeelmohamed** [comment]
@beaucronin great, let us know if you run into any issues!
