### ISSUE TITLE
Plan for alternative to request package?

### ISSUE THREAD

**Issue by siwinski** [splunk/splunk-javascript-logging#51]
Given request/request#3142 and the `request` module going into "maintenance mode", is there a plan for using an alternative package for this library?

**Comment by scottux** [comment]
request is also including har-validator which is including ajv, which is making snyk angry.

**Comment by bparmar-splunk** [comment]
Hi @siwinski & @scottux,
**Update**: We are no longer using request library, instead we have used needle.
We recommend you to update the library version and let us know incase of further queries.

We are closing this issue for now.
Thank you.
