### ISSUE TITLE
Losing fields from logged event

### ISSUE THREAD

**Issue by ecowden** [splunk/splunk-javascript-logging#7]
I'm probably just using this library wrong, but I can't seem to send the event I want to send to the HTTP event collector.

I want to send a logging event with an `event` attribute including both a message and metadata like,

```json
{
    "time": 1426279439, 
    "host": "...",
    "source": "...",
    "sourcetype": "...",
    "index": "...",
    "event": { 
      "message": "logging message goes here",
      "app": "some miscellaneous metadata",
      "moreMetadata": "actually, there's lots of metadata for the event",
      "severity": "info"
   }
}
```

I've tried several ways to interact with the `Logger.send(...)` method without success. First:

```js
const payload = {
  message: "logging message goes here",
  app: "some miscellaneous metadata",
  moreMetadata: "actually, there's lots of metadata for the event",
  severity: "info"
}
splunkLogger.send(payload, err => {
  // ...
})
```

The event that makes it into splunk is just the "message" and "severity" fields. I can confirm that the request sent from the library, [splunklogger.js:459](https://github.com/splunk/splunk-javascript-logging/blob/master/splunklogger.js#L459), is missing the extra metadata fields:

```js
{ json: true,
  strictSSL: false,
  headers: 
   { Authorization: 'xxxxx',
      'Content-Type': 'application/x-www-form-urlencoded' },
   body: '{"time":"1465482320.275","event":{"message":"logging message goes here","severity":"info"}}',
   url: 'http://...' }
```

... and the result in Splunk:

<img width="513" alt="screen shot 2016-06-09 at 9 32 22 am" src="https://cloud.githubusercontent.com/assets/1668988/15933392/424cad74-2e25-11e6-8da7-6b3a5df5c2fc.png">

I've also tried putting the metadata under, `metadata`, but that seems to be reserved for `source`, `sourcetype`, `index` and `host`.

I've also tried putting all the the info under an additional `message` attribute:

```js
const payload = {
  message: {
    message: "logging message goes here",
    app: "some miscellaneous metadata",
    moreMetadata: "actually, there's lots of metadata for the event",
    severity: "info"
  }
}
splunkLogger.send(payload, err => {
  // ...
})
```

...and while it does come through...

<img width="1041" alt="screen shot 2016-06-09 at 9 37 16 am" src="https://cloud.githubusercontent.com/assets/1668988/15933554/cb2be272-2e25-11e6-855c-540556e65a7d.png">

...we don't want those fields to be `message.message` or `message.app`, we really want it at the top level.

I can create and POST the event I want directly to the endpoint and it works as expected. Is there any way to do it with this library?

**Comment by glennblock** [comment]
Hi @ecowden 

By default we sent in the format that you are seeing, with your custom payload under "message". You can however provide a custom formatter in a few lines of code to send in your own custom format and have complete control. If you look at this [https://github.com/splunk/splunk-javascript-logging/blob/master/test/test_send.js#L1816 test]

**Comment by ecowden** [comment]
Ahh, now I see what that formatter does...

In case anyone else stumbles across this, I got this working by using a formatter like:

```js
logger.eventFormatter = function (message, severity) {
  return message
}
```

...and passing in the event I want under `message`, like:

```js
const event = {
  message: "logging message goes here",
  app: "some miscellaneous metadata",
  moreMetadata: "actually, there's lots of metadata for the event",
  severity: "info"
}
splunkLogger.send({ message: event }, err => {
  // ...
})
```

Thanks!

**Comment by glennblock** [comment]
👍
