### ISSUE TITLE
Content-type is being set to application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by bbultman** [splunk/splunk-javascript-logging#9]
Hi there! 

Just found an issue using this package.

Lib: Splunk-logging v0.9.1
OS: MacOS 10.11.6
Node: 6.4.0
Splunk: 6.5.0

We're using a node script to send JSON data to splunk, and it's been working fine. Now I've stumbled upon an issue where the text includes parentheses inside a string.

For example, this: 
`id:329,build:(id:164979)`
becomes:
`id:329,build:%28id:164979%29`
(as seen inside splunk)

I've isolated the issue to splunk-logging/splunklogger.js line 435, row 47.

The content-type is set to application/x-www-form-urlencoded, even though the default options for the request module include `"json": true`

I hope that line 435 can be removed entirely. It makes no sense to me -- both indirectly setting the content-type to json, and then explicitly setting it to x-www-form-urlencoded afterwards.

**Comment by shakeelmohamed** [comment]
Hi @bbultman,

I believe we needed that header to workaround a bug in Splunk 6.3.
The right fix would be adding a config setting to determine if we want to set the `application/x-www-form-urlencoded` header, and default to not sending it.

Is this blocking you? If so, we're open to a pull request

**Comment by bbultman** [comment]
It's somewhat urgent, but I need to wait for approval (company needs to sign the contribution agreement, etc). I'll be fixing this today (as per your recommendation), and if possible I'll create a PR for the fix in the future.

**Comment by shakeelmohamed** [comment]
@bbultman That sounds like a plan. If needed, you can always fork and modify the library for a quick fix. I'll see about prioritizing the change internally

**Comment by shakeelmohamed** [comment]
@bbultman after digging through this today, it looks like this URL encoding is "forced" upon us by the request library we use under the hood. I'm looking into our options

**Comment by shakeelmohamed** [comment]
We've just released v0.9.2 with this fix. Give it a try!
